---
all: 
    children:
          Routers:
                hosts:
                  router1:
                    ansible_host: 127.0.0.1
                    ansible_port: 2202
                    ansible_private_key_file: /root/OTUS/Kazay/OSPF/OSPF/.vagrant/machines/router1/virtualbox/private_key
                  router2:
                      ansible_host: 127.0.0.1
                      ansible_port: 2203
                      ansible_private_key_file: /root/OTUS/Kazay/OSPF/OSPF/.vagrant/machines/router2/virtualbox/private_key
                  router3:
                      ansible_host: 127.0.0.1
                      ansible_port: 2204
                      ansible_private_key_file: /root/OTUS/Kazay/OSPF/OSPF/.vagrant/machines/router3/virtualbox/private_key
      