---
- name: OSPF
  hosts: Routers
  become: yes
  vars_files: defaults/main.yml
  tasks:
  - name: install tools
    apt:
      name:
        - tcpdump
        - net-tools
        - traceroute
        - nano
      state: present
      update_cache: true

  - name: disable ufw service 
    service:
      name: ufw 
      state: stopped 
      enabled: false

  - name: add gpg frrouting.org 
    apt_key:
      url: "https://deb.frrouting.org/frr/keys.asc" 
      state: present

  - name: add frr repo 
    apt_repository:
      repo: 'deb https://deb.frrouting.org/frr {{ ansible_distribution_release }} frr-stable'
      state: present

  - name: install FRR packages 
    apt:
     name:
      - frr
      - frr-pythontools 
     state: present 
     update_cache: true

  - name: set up forward packages across routers 
    sysctl:
      name: net.ipv4.conf.all.forwarding 
      value: '1'
      state: present
  
  # - name: set up asynchronous routing 
  #   sysctl:
  #     name: net.ipv4.conf.all.rp_filter
  #     value: '0'
  #     state: present
  - name: set up asynchronous routing 
    shell: sysctl -w net.ipv4.conf.all.rp_filter=0
    become: root

  - name: base set up OSPF 
    template:
      src: templates/daemons.j2
      dest: /etc/frr/daemons 
      owner: frr
      group: frr
      mode: 0640

  - name: set up OSPF 
    template:
      src: templates/frr.conf.j2
      dest: /etc/frr/frr.conf 
      owner: frr
      group: frr
      mode: 0640
    tags: 
      - setup_routing

  - name: restart FRR 
    service:
      name: frr
      state: restarted 
      enabled: true
    tags: 
      - setup_routing



